<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Market.Domain\Market.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <MessagingPackagesVersion>1.0.0.17</MessagingPackagesVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Messaging.Abstractions" Version="$(MessagingPackagesVersion)" />
    <PackageReference Include="Messaging.Contracts" Version="$(MessagingPackagesVersion)" />
  </ItemGroup>

</Project>
