location = /accounts {
    return 301 /accounts/;
}

location /accounts/ {
    proxy_pass http://accountsloginweb:8080;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location = /accounts-management {
    return 301 /accounts-management/;
}

location /accounts-management/ {
    proxy_pass http://accountsmanagementweb:8080;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
location = / {
    return 301 /market/;
}
location = /market {
    return 301 /market/;
}

location /market/ {
    proxy_pass http://marketweb:80;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
