CREATE TABLE "Store" (
    "Id" UUID PRIMARY KEY,
    "CreatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    "DeletedAt" TIMESTAMP WITHOUT TIME ZONE NULL,
    "Name" VARCHAR(255) NOT NULL,
    "Description" TEXT NULL,
    "UserCreatedId" UUID NOT NULL,
    "Status" INT NOT NULL
);
