CREATE TABLE "ErrorLog" (
    "Id" UUID PRIMARY KEY,
    "CreatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    "DeletedAt" TIMESTAMP WITHOUT TIME ZONE NULL,
    "Source" VARCHAR(255) NOT NULL,
    "Message" TEXT NOT NULL,
    "StackTrace" TEXT NOT NULL,
    "RequestPath" VARCHAR(500) NOT NULL,
    "HttpMethod" VARCHAR(20) NOT NULL,
    "Status" INT NOT NULL
);
